apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: shestera/scaletestapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "20Mi"
          limits:
            memory: "20Mi"
